spring.application.name=ArtVista
spring.datasource.url=jdbc:mysql://localhost:3306/artvista
spring.datasource.username=root
spring.datasource.password=root
# spring.datasource.password=W7301@jqir#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
admin.emails=senargha679@gmail.com,ninjaniladri@gmail.com
admin.password=admin123